version: '3'
services:
  app:
   container_name: company_info 
   build: .
   ports:
    - 9000:9000
   restart: on-failure
   volumes:
     - api:/usr/src/app/
   depends_on:
     - fullstack-mysql
   networks:
      - fullstack

  fullstack-mysql:
    image: mysql:latest
    container_name: full_db_mysql
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=localhost 
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=company_info
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack


volumes:
  api:
  database_mysql:   

networks:
  fullstack:
    driver: bridge