version: '3'
services:
  app:
   container_name: company 
   build: .
   ports:
    - 9000:9000
   restart: on-failure
   volumes:
     - api:/usr/src/app/
   depends_on:
     - db_mysql
   networks:
      - fullstack

  db_mysql:
    image: mysql:latest
    restart: on-failure
    container_name: db_mysql
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=company_info
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack


volumes:
  api:
  database_mysql:   

networks:
  fullstack:
    driver: bridge